#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Build Raspberry Pi 2 Offical OpenWrt Toolchain

on:
  repository_dispatch:
    types: [offical, rpi2]
  workflow_dispatch:
  schedule:
    - cron: 0 18 * * *
#  watch:
#    types: started

jobs:
  Build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        df -hT $PWD
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "Asia/Shanghai"
        echo "PROJECTROOT=$PWD" >> $GITHUB_ENV

    - name: Pull & Run OpenWrt-Env Container
      run: |
        docker run -itd --name openwrtenv-offical sulinggg/openwrtenv:latest
        docker cp $PROJECTROOT/scripts/offical openwrtenv-offical:/home/admin/scripts
        docker cp $PROJECTROOT/config/offical openwrtenv-offical:/home/admin/config

    - name: Compile Toolchain For Raspberry Pi 2
      run: |
        docker exec openwrtenv-offical bash -c "sudo chown -R admin:admin /home/admin && chmod +x /home/admin/scripts/*.sh"
        docker exec openwrtenv-offical bash -c "git clone --depth 1 https://github.com/openwrt/openwrt -b master openwrt"
        docker exec openwrtenv-offical bash -c "cp /home/admin/scripts/* /home/admin/openwrt"
        docker exec openwrtenv-offical /home/admin/openwrt/build-rpi2-offical-openwrt-toolchain.sh

    - name: Docker Commit
      run: |
        docker commit openwrtenv-offical ${{ secrets.DOCKERHUB_USERNAME }}/openwrtenv:offical-rpi2
        df -hT $PWD

    - name: Push Docker Image To Dockerhub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/openwrtenv:offical-rpi2
      
    - name: Push Docker Image To Aliyun Docker Registry
      run: |
        docker login -u ${{ secrets.ALIYUN_USERNAME }} -p ${{ secrets.ALIYUN_PASSWORD }} registry.cn-hongkong.aliyuncs.com
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/openwrtenv:offical-rpi2 registry.cn-hongkong.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACES }}/openwrtenv:offical-rpi2
        docker push registry.cn-hongkong.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACES }}/openwrtenv:offical-rpi2
