#==================================================
# https://github.com/P3TERX/openwrt-build-env
# Description: OpenWrt build environment in docker
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com (chinese)
#==================================================
name: Docker Images Build & Publish

on:
  repository_dispatch:
    types: [Manual*, Auto* ,test]
  push:
    paths:
      - 'Dockerfile'
  schedule:
    - cron: 10 22 * * 5

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build & Push Docker Image To Dockerhub
      uses: docker/build-push-action@v1
      with:
        push: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: sulinggg/openwrtenv
        tags: full
        dockerfile: Dockerfile
        path: .

    - name: Push Docker Image To Aliyun Docker Registry
      run: |
        docker login -u ${{ secrets.ALIYUN_USERNAME }} -p ${{ secrets.ALIYUN_PASSWORD }} registry.cn-hongkong.aliyuncs.com
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/openwrtenv:full registry.cn-hongkong.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACES }}/openwrtenv:full
        docker push registry.cn-hongkong.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACES }}/openwrtenv:full
